[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitstring>=4.3.1",
    "loguru>=0.7.3",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
]
